<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="282" started-at="2019-03-14T10:45:27Z" finished-at="2019-03-14T10:45:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="282" started-at="2019-03-14T10:45:27Z" finished-at="2019-03-14T10:45:28Z">
      <class name="com.VendingMachine.VendingMachineTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="setUp" is-config="true" duration-ms="40" started-at="2019-03-14T10:45:27Z" finished-at="2019-03-14T10:45:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testBuyItemWithExactPrice()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testBuyItemWithExactPrice" duration-ms="38" started-at="2019-03-14T10:45:27Z" finished-at="2019-03-14T10:45:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBuyItemWithExactPrice -->
        <test-method status="PASS" signature="testBuyItemWithMorePrice()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testBuyItemWithMorePrice" duration-ms="10" started-at="2019-03-14T10:45:27Z" finished-at="2019-03-14T10:45:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBuyItemWithMorePrice -->
        <test-method status="FAIL" signature="testNotSufficientChangeException()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testNotSufficientChangeException" duration-ms="5" started-at="2019-03-14T10:45:28Z" finished-at="2019-03-14T10:45:28Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method VendingMachineTest.testNotSufficientChangeException()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad] should have thrown an exception of type class com.VendingMachine.NotSufficientChangeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method VendingMachineTest.testNotSufficientChangeException()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad] should have thrown an exception of type class com.VendingMachine.NotSufficientChangeException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1139)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNotSufficientChangeException -->
        <test-method status="PASS" signature="testRefund()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testRefund" duration-ms="7" started-at="2019-03-14T10:45:28Z" finished-at="2019-03-14T10:45:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRefund -->
        <test-method status="PASS" signature="testReset()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testReset" duration-ms="10" started-at="2019-03-14T10:45:28Z" finished-at="2019-03-14T10:45:28Z">
          <exception class="com.VendingMachine.SoldOutException">
            <message>
              <![CDATA[Sold Out, Please buy another item]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.VendingMachine.SoldOutException: Sold Out, Please buy another item
at com.VendingMachine.VendingMachineImpl.SelectItemAndGetPrice(VendingMachineImpl.java:37)
at com.VendingMachine.VendingMachineTest.testReset(VendingMachineTest.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.VendingMachine.SoldOutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReset -->
        <test-method status="FAIL" signature="testSoldOut()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="testSoldOut" duration-ms="8" started-at="2019-03-14T10:45:28Z" finished-at="2019-03-14T10:45:28Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method VendingMachineTest.testSoldOut()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad] should have thrown an exception of type class com.VendingMachine.SoldOutException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method VendingMachineTest.testSoldOut()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad] should have thrown an exception of type class com.VendingMachine.SoldOutException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1139)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSoldOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.VendingMachine.VendingMachineTest@7dc7cbad]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-03-14T10:45:28Z" finished-at="2019-03-14T10:45:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.VendingMachine.VendingMachineTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
